name: todo_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  rxdart: ^0.27.4
  path_provider: ^2.0.9
  sqflite: ^2.0.2
  flutter_launcher_icons: ^0.9.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/images/app_bar/
    - assets/images/onboarding/




  fonts:
    - family: fontEn
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: fontEnBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: fontAr
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
    - family: fontArBold
      fonts:
        - asset: assets/fonts/Almarai-Bold.ttf
